#!/usr/bin/env python3
"""
make_map_previews.py: downscaled PNG previews of the map pages, for browsing on GitHub.

Reads   viina/qgis/maps/NN_<name>.png   (written by build_qgis_project.py)
Writes  viina/qgis/maps/preview/NN_<name>.png   (max 1600 px wide, 256-colour palette)
        viina/qgis/maps/preview/README.md       (index of all previews present)

Usage (venv python, from any directory):
    python viina/make_map_previews.py              # default set: pages cleared for publication
    python viina/make_map_previews.py 05 06        # explicit pages (held-back pages are refused)

Pages held back are refused even when named, and are also excluded in .gitignore.
Full-resolution PNGs and PDFs stay out of git (GitHub release assets / Zenodo).
"""
import sys
from pathlib import Path

from PIL import Image

HERE = Path(__file__).resolve().parent
MAPS = HERE / "qgis" / "maps"
OUT = MAPS / "preview"
WIDTH = 1600

# hromada- or oblast-level choropleths, cleared for publication
DEFAULT = ["04", "11", "13", "14", "15", "16", "17"]

# never previewed until the reason is resolved (mirrors .gitignore section 3 / 4b)
HELD = {
    "01": "risk index with strike detail, last 12 months (R5 review)",
    "02": "strikes by settlement, last 12 months (R1/R5)",
    "03": "strike points, last 12 months (R5)",
    "18": "IOM DTM and reSCORE context (upstream terms)",
    "19": "recent light level, last 12 months (R2)",
    "20": "change class to the most recent 12 months (R2)",
    "05": "strike points, last 12 months, on H3 r7 cells (R1/R5)",
    "06": "interpolated strike surface, 5 km grid, marks reported targets (R1/R3)",
    "07": "interpolated strike surfaces (R1)",
    "08": "interpolated strike surfaces (R1/R3)",
    "09": "interpolated alert surface; hromada choropleth is page 04 (R1)",
    "10": "kernel density from event locations (R1/R5)",
    "12": "kernel density on 1 km grid with strike points (R1/R5)",
}

ATTRIBUTION = ("Data: VIINA 2.0 (ODbL); air-raid alert records, V. Klymenko (MIT); OCHA COD-AB / "
               "SSPE Kartographia (CC BY-IGO); openbudget.gov.ua; NASA Black Marble; JRC GHS-POP; "
               "DREAM. Analysis and maps: M. Garand, UBEC Platform, CC BY 4.0.")


def find_source(page):
    hits = sorted(MAPS.glob(f"{page}_*.png"))
    if len(hits) != 1:
        sys.exit(f"page {page}: expected exactly one {page}_*.png in {MAPS}, found {len(hits)}")
    return hits[0]


def make_preview(src, dst):
    with Image.open(src) as im:
        im.load()
        if im.mode in ("RGBA", "LA", "P"):
            im = im.convert("RGBA")
            bg = Image.new("RGB", im.size, (255, 255, 255))
            bg.paste(im, mask=im.getchannel("A"))
            im = bg
        else:
            im = im.convert("RGB")
        if im.width > WIDTH:
            h = round(im.height * WIDTH / im.width)
            im = im.resize((WIDTH, h), Image.Resampling.LANCZOS)
        pal = im.quantize(colors=256, method=Image.Quantize.MEDIANCUT)
        pal.save(dst, format="PNG", optimize=True)
        return im.size


def write_index():
    files = sorted(OUT.glob("[0-9][0-9]_*.png"))
    lines = [
        "# Map previews",
        "",
        "Downscaled previews of the QGIS atlas pages, generated by `viina/make_map_previews.py`.",
        "Full-resolution PNG and PDF pages are published as release assets, not in git.",
        "",
        f"> {ATTRIBUTION}",
        "",
        "Pages held back pending review:",
        "",
    ] + [f"- {p}: {why}" for p, why in HELD.items()] + [
        "",
    ]
    for f in files:
        title = f.stem[3:].replace("_", " ")
        lines += [f"## {f.stem[:2]} · {title}", "", f"![{title}]({f.name})", ""]
    (OUT / "README.md").write_text("\n".join(lines), encoding="utf-8")
    return len(files)


def main():
    pages = [a.zfill(2) for a in sys.argv[1:]] or DEFAULT
    refused = [p for p in pages if p in HELD]
    if refused:
        sys.exit("held back, not previewed: " + "; ".join(f"{p}: {HELD[p]}" for p in refused))
    OUT.mkdir(exist_ok=True)
    total = 0
    for p in pages:
        src = find_source(p)
        dst = OUT / src.name
        w, h = make_preview(src, dst)
        kb = dst.stat().st_size / 1024
        total += kb
        print(f"{src.name}: {src.stat().st_size / 1048576:.1f} MB -> {w}x{h}, {kb:.0f} KB")
    n = write_index()
    print(f"previews written: {len(pages)} ({total / 1024:.1f} MB); index lists {n} pages")


if __name__ == "__main__":
    main()
