<!DOCTYPE qgis PUBLIC 'http://mrcc.com/qgis.dtd' 'SYSTEM'>
<qgis version="3.40" styleCategories="Symbology">
<renderer-v2 type="categorizedSymbol" attr="bv_alt" symbollevels="0" enableorderby="0" forceraster="0">
<categories>
<category value="11" symbol="0" label="low exposure · low capacity" render="true"/>
<category value="12" symbol="1" label="low exposure · medium capacity" render="true"/>
<category value="13" symbol="2" label="low exposure · high capacity" render="true"/>
<category value="21" symbol="3" label="medium exposure · low capacity" render="true"/>
<category value="22" symbol="4" label="medium exposure · medium capacity" render="true"/>
<category value="23" symbol="5" label="medium exposure · high capacity" render="true"/>
<category value="31" symbol="6" label="high exposure · low capacity" render="true"/>
<category value="32" symbol="7" label="high exposure · medium capacity" render="true"/>
<category value="33" symbol="8" label="high exposure · high capacity" render="true"/>
<category value="occ" symbol="9" label="occupied" render="true"/>
<category value="na" symbol="10" label="no data" render="true"/>
</categories>
<symbols>
<symbol type="fill" name="0" alpha="1" clip_to_extent="1" force_rhr="0"><layer class="SimpleFill" enabled="1" locked="0" pass="0"><Option type="Map"><Option name="color" type="QString" value="232,232,232,255"/><Option name="outline_color" type="QString" value="255,255,255,255"/><Option name="outline_style" type="QString" value="solid"/><Option name="outline_width" type="QString" value="0.05"/><Option name="outline_width_unit" type="QString" value="MM"/><Option name="style" type="QString" value="solid"/></Option></layer></symbol>
<symbol type="fill" name="1" alpha="1" clip_to_extent="1" force_rhr="0"><layer class="SimpleFill" enabled="1" locked="0" pass="0"><Option type="Map"><Option name="color" type="QString" value="172,228,228,255"/><Option name="outline_color" type="QString" value="255,255,255,255"/><Option name="outline_style" type="QString" value="solid"/><Option name="outline_width" type="QString" value="0.05"/><Option name="outline_width_unit" type="QString" value="MM"/><Option name="style" type="QString" value="solid"/></Option></layer></symbol>
<symbol type="fill" name="2" alpha="1" clip_to_extent="1" force_rhr="0"><layer class="SimpleFill" enabled="1" locked="0" pass="0"><Option type="Map"><Option name="color" type="QString" value="90,200,200,255"/><Option name="outline_color" type="QString" value="255,255,255,255"/><Option name="outline_style" type="QString" value="solid"/><Option name="outline_width" type="QString" value="0.05"/><Option name="outline_width_unit" type="QString" value="MM"/><Option name="style" type="QString" value="solid"/></Option></layer></symbol>
<symbol type="fill" name="3" alpha="1" clip_to_extent="1" force_rhr="0"><layer class="SimpleFill" enabled="1" locked="0" pass="0"><Option type="Map"><Option name="color" type="QString" value="223,176,214,255"/><Option name="outline_color" type="QString" value="255,255,255,255"/><Option name="outline_style" type="QString" value="solid"/><Option name="outline_width" type="QString" value="0.05"/><Option name="outline_width_unit" type="QString" value="MM"/><Option name="style" type="QString" value="solid"/></Option></layer></symbol>
<symbol type="fill" name="4" alpha="1" clip_to_extent="1" force_rhr="0"><layer class="SimpleFill" enabled="1" locked="0" pass="0"><Option type="Map"><Option name="color" type="QString" value="165,173,211,255"/><Option name="outline_color" type="QString" value="255,255,255,255"/><Option name="outline_style" type="QString" value="solid"/><Option name="outline_width" type="QString" value="0.05"/><Option name="outline_width_unit" type="QString" value="MM"/><Option name="style" type="QString" value="solid"/></Option></layer></symbol>
<symbol type="fill" name="5" alpha="1" clip_to_extent="1" force_rhr="0"><layer class="SimpleFill" enabled="1" locked="0" pass="0"><Option type="Map"><Option name="color" type="QString" value="86,152,185,255"/><Option name="outline_color" type="QString" value="255,255,255,255"/><Option name="outline_style" type="QString" value="solid"/><Option name="outline_width" type="QString" value="0.05"/><Option name="outline_width_unit" type="QString" value="MM"/><Option name="style" type="QString" value="solid"/></Option></layer></symbol>
<symbol type="fill" name="6" alpha="1" clip_to_extent="1" force_rhr="0"><layer class="SimpleFill" enabled="1" locked="0" pass="0"><Option type="Map"><Option name="color" type="QString" value="190,100,172,255"/><Option name="outline_color" type="QString" value="255,255,255,255"/><Option name="outline_style" type="QString" value="solid"/><Option name="outline_width" type="QString" value="0.05"/><Option name="outline_width_unit" type="QString" value="MM"/><Option name="style" type="QString" value="solid"/></Option></layer></symbol>
<symbol type="fill" name="7" alpha="1" clip_to_extent="1" force_rhr="0"><layer class="SimpleFill" enabled="1" locked="0" pass="0"><Option type="Map"><Option name="color" type="QString" value="140,98,170,255"/><Option name="outline_color" type="QString" value="255,255,255,255"/><Option name="outline_style" type="QString" value="solid"/><Option name="outline_width" type="QString" value="0.05"/><Option name="outline_width_unit" type="QString" value="MM"/><Option name="style" type="QString" value="solid"/></Option></layer></symbol>
<symbol type="fill" name="8" alpha="1" clip_to_extent="1" force_rhr="0"><layer class="SimpleFill" enabled="1" locked="0" pass="0"><Option type="Map"><Option name="color" type="QString" value="59,73,148,255"/><Option name="outline_color" type="QString" value="255,255,255,255"/><Option name="outline_style" type="QString" value="solid"/><Option name="outline_width" type="QString" value="0.05"/><Option name="outline_width_unit" type="QString" value="MM"/><Option name="style" type="QString" value="solid"/></Option></layer></symbol>
<symbol type="fill" name="9" alpha="1" clip_to_extent="1" force_rhr="0"><layer class="SimpleFill" enabled="1" locked="0" pass="0"><Option type="Map"><Option name="color" type="QString" value="189,189,189,255"/><Option name="outline_color" type="QString" value="255,255,255,255"/><Option name="outline_style" type="QString" value="solid"/><Option name="outline_width" type="QString" value="0.05"/><Option name="outline_width_unit" type="QString" value="MM"/><Option name="style" type="QString" value="solid"/></Option></layer></symbol>
<symbol type="fill" name="10" alpha="1" clip_to_extent="1" force_rhr="0"><layer class="SimpleFill" enabled="1" locked="0" pass="0"><Option type="Map"><Option name="color" type="QString" value="255,255,255,255"/><Option name="outline_color" type="QString" value="255,255,255,255"/><Option name="outline_style" type="QString" value="solid"/><Option name="outline_width" type="QString" value="0.05"/><Option name="outline_width_unit" type="QString" value="MM"/><Option name="style" type="QString" value="solid"/></Option></layer></symbol>
</symbols>
</renderer-v2>
</qgis>
